// backend/src/modules/scales/seeds/mmse.seed.ts
import type {
  ScaleSeedData,
  ScaleSeedDefinition,
  ScaleSeedVersion,
} from './scale-seed.types';

export const MMSE_SCALE_DEFINITION_SEED: ScaleSeedDefinition = {
  code: 'mmse',
  name: '简易精神状态评价量表',
  shortName: 'MMSE',
  description:
    'MMSE 初始配置种子数据，依据 MMSE+MoCA.pdf 建立内部只读配置底座。',
  category: 'cognitive',
  status: 'active',
  sortOrder: 10,
  tags: ['cognitive', 'screening', 'mmse'],
};

export const MMSE_SCALE_VERSION_SEED: ScaleSeedVersion = {
  scaleCode: 'mmse',
  version: '1.0',
  displayVersion: 'CRF 1.0',
  crfVersion: '1.0',
  scoringRuleVersion: 'mmse-crf-1.0',
  fieldEncodingVersion: 'mmse-semantic-1.0',
  sourceDocument: 'MMSE+MoCA.pdf',
  status: 'active',
  totalScoreRange: { min: 0, max: 30, step: 1 },
  groups: [
    {
      code: 'orientation',
      title: '定向力',
      order: 1,
      instruction: '记录时间和地点定向的结构化子项。',
      description: '时间定向 5 分，地点定向 5 分。',
      cognitiveDomainCodes: ['orientation'],
    },
    {
      code: 'immediate_recall',
      title: '即刻回忆',
      order: 2,
      instruction: '记录三个词的即时复述表现。',
      description: '每个词 1 分。',
      cognitiveDomainCodes: ['memory'],
    },
    {
      code: 'attention_calculation',
      title: '注意力和计算力',
      order: 3,
      instruction: '记录连续减 7 的五个步骤。',
      description: '每一步独立计分。',
      cognitiveDomainCodes: ['attention_calculation'],
    },
    {
      code: 'delayed_recall',
      title: '回忆',
      order: 4,
      instruction: '记录三个词的延迟回忆表现。',
      description: '每个词 1 分。',
      cognitiveDomainCodes: ['memory'],
    },
    {
      code: 'language',
      title: '语言',
      order: 5,
      instruction: '记录命名、重复、阅读执行、三步指令和书写表达。',
      description: '语言相关项目合计 8 分。',
      cognitiveDomainCodes: ['language'],
    },
    {
      code: 'visuospatial',
      title: '视空间 / 绘图',
      order: 6,
      instruction: '记录图形复制结果及图片 / 手写证据。',
      description: '绘图 1 分。',
      cognitiveDomainCodes: ['visuospatial'],
    },
  ],
  items: [
    {
      code: 'mmse.orientation.time',
      crfCode: 'MMSE.1.time',
      title: '时间定向',
      prompt: '询问年份、季节、月份、日期和星期。',
      instruction: '每个时间定向子项正确得 1 分。',
      order: 1,
      groupCode: 'orientation',
      responseType: 'multi_choice',
      scoreRange: { min: 0, max: 5, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['orientation'],
      evidenceTypes: ['operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: false,
      supportsHandwriting: false,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'structured_manual',
        sourceDocument: 'MMSE+MoCA.pdf',
        subItems: [
          { code: 'mmse.orientation.year', title: '年', maxScore: 1 },
          { code: 'mmse.orientation.season', title: '季节', maxScore: 1 },
          { code: 'mmse.orientation.month', title: '月份', maxScore: 1 },
          { code: 'mmse.orientation.date', title: '日期', maxScore: 1 },
          { code: 'mmse.orientation.weekday', title: '星期', maxScore: 1 },
        ],
      },
      qualityControlRule: {
        requireStructuredSubItems: true,
      },
      reportingRule: {
        showInReport: true,
        groupLabel: '定向力',
      },
      researchExportField: 'mmse_orientation_time_score',
    },
    {
      code: 'mmse.orientation.place',
      crfCode: 'MMSE.1.place',
      title: '地点定向',
      prompt: '询问城市、区/城区、街道、楼层和当前地点。',
      instruction: '每个地点定向子项正确得 1 分。',
      order: 2,
      groupCode: 'orientation',
      responseType: 'multi_choice',
      scoreRange: { min: 0, max: 5, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['orientation'],
      evidenceTypes: ['operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: false,
      supportsHandwriting: false,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'structured_manual',
        sourceDocument: 'MMSE+MoCA.pdf',
        subItems: [
          { code: 'mmse.orientation.city', title: '城市', maxScore: 1 },
          { code: 'mmse.orientation.district', title: '区/城区', maxScore: 1 },
          { code: 'mmse.orientation.street', title: '街道', maxScore: 1 },
          { code: 'mmse.orientation.floor', title: '楼层', maxScore: 1 },
          { code: 'mmse.orientation.location', title: '地点', maxScore: 1 },
        ],
      },
      qualityControlRule: {
        requireStructuredSubItems: true,
      },
      reportingRule: {
        showInReport: true,
        groupLabel: '定向力',
      },
      researchExportField: 'mmse_orientation_place_score',
    },
    {
      code: 'mmse.memory.immediate_recall',
      crfCode: 'MMSE.2',
      title: '即刻回忆',
      prompt: '说出皮球、国旗、树木三个词，请受试者立即复述。',
      instruction: '每个词正确复述得 1 分。',
      order: 3,
      groupCode: 'immediate_recall',
      responseType: 'multi_choice',
      scoreRange: { min: 0, max: 3, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['memory'],
      evidenceTypes: ['raw_text', 'operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: false,
      supportsHandwriting: false,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'structured_manual',
        words: [
          { code: 'mmse.memory.immediate_recall.ball', text: '皮球' },
          { code: 'mmse.memory.immediate_recall.flag', text: '国旗' },
          { code: 'mmse.memory.immediate_recall.tree', text: '树木' },
        ],
        scoringSummary: '每个词正确回忆 1 分。',
      },
      qualityControlRule: {
        preserveRawText: true,
      },
      reportingRule: {
        showInReport: true,
        groupLabel: '即刻回忆',
      },
      researchExportField: 'mmse_memory_immediate_recall_score',
    },
    {
      code: 'mmse.attention.serial_sevens',
      crfCode: 'MMSE.3',
      title: '连续减 7',
      prompt: '请从 100 开始连续减 7。',
      instruction: '记录五步答案：93、86、79、72、65。',
      order: 4,
      groupCode: 'attention_calculation',
      responseType: 'multi_step_calculation',
      scoreRange: { min: 0, max: 5, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['attention_calculation'],
      evidenceTypes: ['raw_text', 'operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: false,
      supportsHandwriting: false,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'multi_step_manual',
        independentStepScoring: true,
        scoringSummary: '每一步独立计分，前一步错误不影响后续评分。',
        steps: [
          {
            code: 'mmse.attention.serial_sevens.step_1',
            expected: 93,
            maxScore: 1,
          },
          {
            code: 'mmse.attention.serial_sevens.step_2',
            expected: 86,
            maxScore: 1,
          },
          {
            code: 'mmse.attention.serial_sevens.step_3',
            expected: 79,
            maxScore: 1,
          },
          {
            code: 'mmse.attention.serial_sevens.step_4',
            expected: 72,
            maxScore: 1,
          },
          {
            code: 'mmse.attention.serial_sevens.step_5',
            expected: 65,
            maxScore: 1,
          },
        ],
      },
      qualityControlRule: {
        requireStepResults: true,
      },
      reportingRule: {
        showInReport: true,
        showStepResults: true,
      },
      researchExportField: 'mmse_attention_serial_sevens_score',
    },
    {
      code: 'mmse.memory.delayed_recall',
      crfCode: 'MMSE.4',
      title: '回忆',
      prompt: '请回忆刚才记住的三个词：皮球、国旗、树木。',
      instruction: '每个词正确回忆得 1 分。',
      order: 5,
      groupCode: 'delayed_recall',
      responseType: 'multi_choice',
      scoreRange: { min: 0, max: 3, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['memory'],
      evidenceTypes: ['raw_text', 'operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: false,
      supportsHandwriting: false,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'structured_manual',
        words: [
          { code: 'mmse.memory.delayed_recall.ball', text: '皮球' },
          { code: 'mmse.memory.delayed_recall.flag', text: '国旗' },
          { code: 'mmse.memory.delayed_recall.tree', text: '树木' },
        ],
      },
      qualityControlRule: {
        preserveRawText: true,
      },
      reportingRule: {
        showInReport: true,
        groupLabel: '回忆',
      },
      researchExportField: 'mmse_memory_delayed_recall_score',
    },
    {
      code: 'mmse.language.naming',
      crfCode: 'MMSE.5',
      title: '命名',
      prompt: '请受试者命名手表和铅笔。',
      instruction: '每个物品命名正确得 1 分。',
      order: 6,
      groupCode: 'language',
      responseType: 'multi_choice',
      scoreRange: { min: 0, max: 2, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['language'],
      evidenceTypes: ['raw_text', 'operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: false,
      supportsHandwriting: false,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'structured_manual',
        subItems: [
          { code: 'mmse.language.naming.watch', expected: '手表', maxScore: 1 },
          {
            code: 'mmse.language.naming.pencil',
            expected: '铅笔',
            maxScore: 1,
          },
        ],
      },
      qualityControlRule: {
        preserveRawText: true,
      },
      reportingRule: {
        showInReport: true,
        groupLabel: '语言',
      },
      researchExportField: 'mmse_language_naming_score',
    },
    {
      code: 'mmse.language.repetition',
      crfCode: 'MMSE.6',
      title: '重复',
      prompt: '请受试者重复指定短句。',
      instruction: '必须完全相同才算正确。',
      order: 7,
      groupCode: 'language',
      responseType: 'text',
      scoreRange: { min: 0, max: 1, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['language'],
      evidenceTypes: ['raw_text', 'operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: false,
      supportsHandwriting: false,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'manual_exact_match',
        scoringSummary: '必须完全相同才算正确。',
      },
      qualityControlRule: {
        preserveRawText: true,
      },
      reportingRule: {
        showInReport: true,
        groupLabel: '语言',
      },
      researchExportField: 'mmse_language_repetition_score',
    },
    {
      code: 'mmse.language.reading_command',
      crfCode: 'MMSE.7',
      title: '阅读并执行',
      prompt: '请受试者阅读并执行“闭上你的眼睛”。',
      instruction: '需有闭眼动作才给分；文盲该项 0 分。',
      order: 8,
      groupCode: 'language',
      responseType: 'boolean',
      scoreRange: { min: 0, max: 1, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['language'],
      evidenceTypes: ['operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: false,
      supportsHandwriting: false,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'manual_observation',
        scoringSummary: '需有闭眼动作才给分；文盲该项 0 分。',
      },
      qualityControlRule: {
        requireOperatorObservation: true,
      },
      reportingRule: {
        showInReport: true,
        groupLabel: '语言',
      },
      researchExportField: 'mmse_language_reading_command_score',
    },
    {
      code: 'mmse.language.three_step_command',
      crfCode: 'MMSE.8',
      title: '三步指令',
      prompt: '请受试者按指令用右手拿纸、对折、放在左腿上。',
      instruction: '每完成一个步骤得 1 分。',
      order: 9,
      groupCode: 'language',
      responseType: 'multi_choice',
      scoreRange: { min: 0, max: 3, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['language'],
      evidenceTypes: ['operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: false,
      supportsHandwriting: false,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'structured_manual',
        subItems: [
          {
            code: 'mmse.language.three_step_command.take_paper',
            title: '右手拿纸',
            maxScore: 1,
          },
          {
            code: 'mmse.language.three_step_command.fold_paper',
            title: '对折',
            maxScore: 1,
          },
          {
            code: 'mmse.language.three_step_command.place_on_left_leg',
            title: '放左腿',
            maxScore: 1,
          },
        ],
      },
      qualityControlRule: {
        requireStructuredSubItems: true,
      },
      reportingRule: {
        showInReport: true,
        groupLabel: '语言',
      },
      researchExportField: 'mmse_language_three_step_command_score',
    },
    {
      code: 'mmse.language.writing_sentence',
      crfCode: 'MMSE.9',
      title: '表达 / 写完整句子',
      prompt: '请受试者写一个完整句子。',
      instruction: '句子需表达完整意思；保留原始文本、图片或手写证据。',
      order: 10,
      groupCode: 'language',
      responseType: 'handwriting',
      scoreRange: { min: 0, max: 1, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['language'],
      evidenceTypes: ['raw_text', 'photo', 'handwriting', 'operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: true,
      supportsHandwriting: true,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'manual_observation',
        scoringSummary: '句子需有主语和谓语，并表达完整意思。',
        sourceCorrection: 'PDF 中该项误写为第 8 项，系统修正为第 9 项。',
      },
      qualityControlRule: {
        correction: 'PDF 中该项误写为第 8 项，系统修正为第 9 项。',
        preserveRawText: true,
        allowPhotoEvidence: true,
        allowHandwritingEvidence: true,
      },
      reportingRule: {
        showInReport: true,
        showEvidence: true,
        correctedCrfItemNo: 9,
      },
      researchExportField: 'mmse_language_writing_sentence_score',
    },
    {
      code: 'mmse.visuospatial.copy_drawing',
      crfCode: 'MMSE.10',
      title: '绘图',
      prompt: '请受试者照样复制图形。',
      instruction: '图形需有 10 个角和 2 条相交直线。',
      order: 11,
      groupCode: 'visuospatial',
      responseType: 'drawing',
      scoreRange: { min: 0, max: 1, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['visuospatial'],
      evidenceTypes: ['photo', 'handwriting', 'operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: true,
      supportsHandwriting: true,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'manual_drawing_review',
        scoringSummary: '图形需有 10 个角和 2 条相交直线。',
        correctedCrfItemNo: 10,
      },
      qualityControlRule: {
        correction: 'MMSE 绘图记录为第 10 项。',
        requireEvidence: ['photo', 'handwriting'],
      },
      reportingRule: {
        showInReport: true,
        showEvidence: true,
        correctedCrfItemNo: 10,
      },
      researchExportField: 'mmse_visuospatial_copy_drawing_score',
    },
  ],
  qualityControlRules: {
    sourceDocument: 'MMSE+MoCA.pdf',
    preserveNonScoredRecords: true,
    corrections: [
      'MMSE 表达项在附件中重复写成第 8 项，系统修正为第 9 项。',
      'MMSE 绘图为第 10 项。',
    ],
    evidenceConsistencyChecks: [
      'supportsPhotoUpload=true 时 evidenceTypes 应包含 photo。',
      'supportsHandwriting=true 时 evidenceTypes 应包含 handwriting。',
    ],
  },
  reportingRules: {
    showTotalScore: true,
    totalScoreField: 'mmse_total_score',
    totalScoreRange: { min: 0, max: 30 },
    showEvidenceForItems: [
      'mmse.language.writing_sentence',
      'mmse.visuospatial.copy_drawing',
    ],
  },
  researchExportMappings: {
    sourceDocument: 'MMSE+MoCA.pdf',
    totalScoreField: 'mmse_total_score',
    itemScoreFields: {
      'mmse.orientation.time': 'mmse_orientation_time_score',
      'mmse.orientation.place': 'mmse_orientation_place_score',
      'mmse.memory.immediate_recall': 'mmse_memory_immediate_recall_score',
      'mmse.attention.serial_sevens': 'mmse_attention_serial_sevens_score',
      'mmse.memory.delayed_recall': 'mmse_memory_delayed_recall_score',
      'mmse.language.naming': 'mmse_language_naming_score',
      'mmse.language.repetition': 'mmse_language_repetition_score',
      'mmse.language.reading_command': 'mmse_language_reading_command_score',
      'mmse.language.three_step_command':
        'mmse_language_three_step_command_score',
      'mmse.language.writing_sentence': 'mmse_language_writing_sentence_score',
      'mmse.visuospatial.copy_drawing': 'mmse_visuospatial_copy_drawing_score',
    },
  },
};

export const MMSE_SCALE_SEED: ScaleSeedData = {
  definition: MMSE_SCALE_DEFINITION_SEED,
  version: MMSE_SCALE_VERSION_SEED,
};
