// backend/src/modules/scales/seeds/moca.seed.ts
import type {
  ScaleSeedData,
  ScaleSeedDefinition,
  ScaleSeedVersion,
} from './scale-seed.types';

export const MOCA_SCALE_DEFINITION_SEED: ScaleSeedDefinition = {
  code: 'moca',
  name: '蒙特利尔认知评估量表',
  shortName: 'MoCA',
  description:
    'MoCA 初始配置种子数据，依据 MMSE+MoCA.pdf 建立内部只读配置底座。',
  category: 'cognitive',
  status: 'active',
  sortOrder: 20,
  tags: ['cognitive', 'screening', 'moca'],
};

export const MOCA_SCALE_VERSION_SEED: ScaleSeedVersion = {
  scaleCode: 'moca',
  version: '1.0',
  displayVersion: 'CRF 1.0',
  crfVersion: '1.0',
  scoringRuleVersion: 'moca-crf-1.0',
  fieldEncodingVersion: 'moca-semantic-1.0',
  sourceDocument: 'MMSE+MoCA.pdf',
  status: 'active',
  totalScoreRange: { min: 0, max: 30, step: 1 },
  groups: [
    {
      code: 'visuospatial_executive',
      title: '视空间与执行功能',
      order: 1,
      instruction: '记录连线、立方体和钟表任务及其证据。',
      description: '视空间与执行功能相关项目合计 5 分。',
      cognitiveDomainCodes: ['visuospatial', 'executive_function'],
    },
    {
      code: 'naming',
      title: '命名',
      order: 2,
      instruction: '记录动物命名表现。',
      description: '命名 3 分。',
      cognitiveDomainCodes: ['language'],
    },
    {
      code: 'memory_immediate',
      title: '即刻记忆',
      order: 3,
      instruction: '记录两次即刻记忆原始表现，不计入总分。',
      description: '即刻记忆用于记录学习过程，不参与总分累加。',
      cognitiveDomainCodes: ['memory'],
    },
    {
      code: 'attention',
      title: '注意',
      order: 4,
      instruction: '记录数字广度、警觉性和连续减 7。',
      description: '注意相关项目合计 6 分。',
      cognitiveDomainCodes: ['attention_calculation'],
    },
    {
      code: 'language',
      title: '语言',
      order: 5,
      instruction: '记录句子复述和词语流畅性。',
      description: '语言相关项目合计 3 分。',
      cognitiveDomainCodes: ['language'],
    },
    {
      code: 'abstraction',
      title: '抽象',
      order: 6,
      instruction: '记录两个抽象概括题。',
      description: '抽象 2 分。',
      cognitiveDomainCodes: ['abstraction'],
    },
    {
      code: 'delayed_recall',
      title: '延迟回忆',
      order: 7,
      instruction: '记录自由回忆、分类提示和多选提示。',
      description: '只有第一遍自由回忆计入得分。',
      cognitiveDomainCodes: ['memory'],
    },
    {
      code: 'orientation',
      title: '定向',
      order: 8,
      instruction: '记录年、月、日、星期、地点和城市。',
      description: '定向 6 分。',
      cognitiveDomainCodes: ['orientation'],
    },
  ],
  items: [
    {
      code: 'moca.visuospatial.trail_making',
      crfCode: 'N1.2.1',
      title: '交替连线测验',
      prompt: '请按 1-一-2-二-3-三-4-四-5-五 顺序连线。',
      instruction: '记录用时、图片和手写轨迹证据。',
      order: 1,
      groupCode: 'visuospatial_executive',
      responseType: 'timed_task',
      scoreRange: { min: 0, max: 1, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['visuospatial', 'executive_function'],
      evidenceTypes: ['photo', 'handwriting', 'duration', 'operator_note'],
      requiresTimer: true,
      supportsPhotoUpload: true,
      supportsHandwriting: true,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'manual_drawing_review',
        scoringSummary:
          '按 1-一-2-二-3-三-4-四-5-五 顺序且无线交叉给 1 分；出现错误且未立即自我纠正给 0 分。',
        evidenceCrfCodes: {
          duration: 'N1.2.1.1',
          photo: 'N1.2.1.2',
        },
      },
      qualityControlRule: {
        requireTimer: true,
        requireEvidence: ['photo', 'handwriting', 'duration'],
      },
      reportingRule: {
        showInReport: true,
        showEvidence: true,
      },
      researchExportField: 'moca_visuospatial_trail_making_score',
    },
    {
      code: 'moca.visuospatial.cube',
      crfCode: 'N1.2.2',
      title: '视空间结构（立方体）',
      prompt: '请照样复制立方体。',
      instruction: '保留图片或平板手写证据。',
      order: 2,
      groupCode: 'visuospatial_executive',
      responseType: 'drawing',
      scoreRange: { min: 0, max: 1, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['visuospatial'],
      evidenceTypes: ['photo', 'handwriting', 'operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: true,
      supportsHandwriting: true,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'manual_drawing_review',
        photoCrfCode: 'N1.2.2.1',
      },
      qualityControlRule: {
        requireEvidence: ['photo', 'handwriting'],
      },
      reportingRule: {
        showInReport: true,
        showEvidence: true,
      },
      researchExportField: 'moca_visuospatial_cube_score',
    },
    {
      code: 'moca.visuospatial.clock',
      crfCode: 'N1.2.3',
      title: '视空间结构（钟表）',
      prompt: '请画钟表，标出所有数字并把指针指向指定时间。',
      instruction: '轮廓、数字和指针各 1 分。',
      order: 3,
      groupCode: 'visuospatial_executive',
      responseType: 'drawing',
      scoreRange: { min: 0, max: 3, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['visuospatial', 'executive_function'],
      evidenceTypes: ['photo', 'handwriting', 'operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: true,
      supportsHandwriting: true,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'structured_drawing_review',
        photoCrfCode: 'N1.2.3.1',
        steps: [
          {
            code: 'moca.visuospatial.clock.contour',
            title: '轮廓',
            maxScore: 1,
          },
          {
            code: 'moca.visuospatial.clock.numbers',
            title: '数字',
            maxScore: 1,
          },
          { code: 'moca.visuospatial.clock.hands', title: '指针', maxScore: 1 },
        ],
      },
      qualityControlRule: {
        requireEvidence: ['photo', 'handwriting'],
      },
      reportingRule: {
        showInReport: true,
        showEvidence: true,
      },
      researchExportField: 'moca_visuospatial_clock_score',
    },
    {
      code: 'moca.language.naming_animals',
      crfCode: 'N1.2.4',
      title: '命名',
      prompt: '请命名图中的动物。',
      instruction: '正确答案摘要：狮子、长颈鹿、骆驼或单峰骆驼。',
      order: 4,
      groupCode: 'naming',
      responseType: 'multi_choice',
      scoreRange: { min: 0, max: 3, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['language'],
      evidenceTypes: ['raw_text', 'operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: false,
      supportsHandwriting: false,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'structured_manual',
        subItems: [
          {
            code: 'moca.language.naming_animals.lion',
            crfCode: 'N1.2.4.1',
            expected: '狮子',
            maxScore: 1,
          },
          {
            code: 'moca.language.naming_animals.giraffe',
            crfCode: 'N1.2.4.2',
            expected: '长颈鹿',
            maxScore: 1,
          },
          {
            code: 'moca.language.naming_animals.camel',
            crfCode: 'N1.2.4.3',
            expected: '骆驼或单峰骆驼',
            maxScore: 1,
          },
        ],
      },
      qualityControlRule: {
        preserveRawText: true,
      },
      reportingRule: {
        showInReport: true,
        groupLabel: '命名',
      },
      researchExportField: 'moca_language_naming_animals_score',
    },
    {
      code: 'moca.memory.immediate.trial_1',
      crfCode: 'N1.2.5.trial_1',
      title: '即刻记忆第一次',
      prompt: '第一次朗读并记录面孔、丝绸、学校、菊花、红色的原始回忆。',
      instruction: '记录原始表现，不计入总分。',
      order: 5,
      groupCode: 'memory_immediate',
      responseType: 'multi_choice',
      scoreRange: { min: 0, max: 0, step: 1 },
      countsTowardTotal: false,
      cognitiveDomainCodes: ['memory'],
      evidenceTypes: ['raw_text', 'operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: false,
      supportsHandwriting: false,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'raw_record_only',
        scoringSummary: '记录原始表现，不计入总分。',
        preserveRawRecord: true,
        words: ['面孔', '丝绸', '学校', '菊花', '红色'],
      },
      qualityControlRule: {
        preserveRawText: true,
        allowNonScoredRecord: true,
      },
      reportingRule: {
        showInReport: true,
        countsTowardTotal: false,
      },
      researchExportField: 'moca_memory_immediate_trial_1_record',
    },
    {
      code: 'moca.memory.immediate.trial_2',
      crfCode: 'N1.2.5.trial_2',
      title: '即刻记忆第二次',
      prompt: '第二次朗读并记录面孔、丝绸、学校、菊花、红色的原始回忆。',
      instruction: '记录原始表现，不计入总分。',
      order: 6,
      groupCode: 'memory_immediate',
      responseType: 'multi_choice',
      scoreRange: { min: 0, max: 0, step: 1 },
      countsTowardTotal: false,
      cognitiveDomainCodes: ['memory'],
      evidenceTypes: ['raw_text', 'operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: false,
      supportsHandwriting: false,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'raw_record_only',
        scoringSummary: '记录原始表现，不计入总分。',
        preserveRawRecord: true,
        words: ['面孔', '丝绸', '学校', '菊花', '红色'],
      },
      qualityControlRule: {
        preserveRawText: true,
        allowNonScoredRecord: true,
      },
      reportingRule: {
        showInReport: true,
        countsTowardTotal: false,
      },
      researchExportField: 'moca_memory_immediate_trial_2_record',
    },
    {
      code: 'moca.attention.digit_span_forward',
      crfCode: 'N1.2.6',
      title: '数字广度顺背',
      prompt: '请顺背数字 21854。',
      instruction: '正确复述数字 21854 得 1 分。',
      order: 7,
      groupCode: 'attention',
      responseType: 'text',
      scoreRange: { min: 0, max: 1, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['attention_calculation'],
      evidenceTypes: ['raw_text', 'operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: false,
      supportsHandwriting: false,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'manual_exact_match',
        expected: '21854',
      },
      qualityControlRule: {
        preserveRawText: true,
      },
      reportingRule: {
        showInReport: true,
        groupLabel: '注意',
      },
      researchExportField: 'moca_attention_digit_span_forward_score',
    },
    {
      code: 'moca.attention.digit_span_backward',
      crfCode: 'N1.2.7',
      title: '数字广度倒背',
      prompt: '请倒背指定数字。',
      instruction: '正确回答摘要为 2-4-7。',
      order: 8,
      groupCode: 'attention',
      responseType: 'text',
      scoreRange: { min: 0, max: 1, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['attention_calculation'],
      evidenceTypes: ['raw_text', 'operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: false,
      supportsHandwriting: false,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'manual_exact_match',
        expected: '2-4-7',
      },
      qualityControlRule: {
        preserveRawText: true,
      },
      reportingRule: {
        showInReport: true,
        groupLabel: '注意',
      },
      researchExportField: 'moca_attention_digit_span_backward_score',
    },
    {
      code: 'moca.attention.vigilance',
      crfCode: 'N1.2.8',
      title: '警觉性',
      prompt: '听到目标字母时做出指定反应。',
      instruction: '完全正确或只有一次错误给 1 分，否则 0 分。',
      order: 9,
      groupCode: 'attention',
      responseType: 'multi_choice',
      scoreRange: { min: 0, max: 1, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['attention_calculation'],
      evidenceTypes: ['operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: false,
      supportsHandwriting: false,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'manual_observation',
        scoringSummary: '完全正确或只有一次错误给 1 分，否则 0 分。',
      },
      qualityControlRule: {
        requireOperatorObservation: true,
      },
      reportingRule: {
        showInReport: true,
        groupLabel: '注意',
      },
      researchExportField: 'moca_attention_vigilance_score',
    },
    {
      code: 'moca.attention.serial_sevens',
      crfCode: 'N1.2.9',
      title: '连续减 7',
      prompt: '请从 100 开始连续减 7。',
      instruction: '记录五步答案：93、86、79、72、65。',
      order: 10,
      groupCode: 'attention',
      responseType: 'multi_step_calculation',
      scoreRange: { min: 0, max: 3, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['attention_calculation'],
      evidenceTypes: ['raw_text', 'operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: false,
      supportsHandwriting: false,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'multi_step_manual',
        independentStepScoring: true,
        scoringSummary:
          '每个计算单独评定，前一步错误不影响后续正确步骤得分；0 个正确 0 分、1 个正确 1 分、2-3 个正确 2 分、4-5 个正确 3 分。',
        aggregationRule: [
          { correctStepCount: 0, score: 0 },
          { correctStepCount: 1, score: 1 },
          { correctStepCountMin: 2, correctStepCountMax: 3, score: 2 },
          { correctStepCountMin: 4, correctStepCountMax: 5, score: 3 },
        ],
        steps: [
          {
            code: 'moca.attention.serial_sevens.step_1',
            expected: 93,
            maxScore: 1,
          },
          {
            code: 'moca.attention.serial_sevens.step_2',
            expected: 86,
            maxScore: 1,
          },
          {
            code: 'moca.attention.serial_sevens.step_3',
            expected: 79,
            maxScore: 1,
          },
          {
            code: 'moca.attention.serial_sevens.step_4',
            expected: 72,
            maxScore: 1,
          },
          {
            code: 'moca.attention.serial_sevens.step_5',
            expected: 65,
            maxScore: 1,
          },
        ],
      },
      qualityControlRule: {
        requireStepResults: true,
      },
      reportingRule: {
        showInReport: true,
        showStepResults: true,
      },
      researchExportField: 'moca_attention_serial_sevens_score',
    },
    {
      code: 'moca.language.sentence_repetition',
      crfCode: 'N1.2.10',
      title: '句子复述',
      prompt: '请准确复述两句话。',
      instruction: '每句话准确复述分别给 1 分。',
      order: 11,
      groupCode: 'language',
      responseType: 'text',
      scoreRange: { min: 0, max: 2, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['language'],
      evidenceTypes: ['raw_text', 'operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: false,
      supportsHandwriting: false,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'structured_manual',
        scoringSummary: '每句话准确复述分别给 1 分。',
        subItems: [
          {
            code: 'moca.language.sentence_repetition.sentence_1',
            crfCode: 'N1.2.10.1',
            maxScore: 1,
          },
          {
            code: 'moca.language.sentence_repetition.sentence_2',
            crfCode: 'N1.2.10.2',
            maxScore: 1,
          },
        ],
      },
      qualityControlRule: {
        preserveRawText: true,
      },
      reportingRule: {
        showInReport: true,
        groupLabel: '语言',
      },
      researchExportField: 'moca_language_sentence_repetition_score',
    },
    {
      code: 'moca.language.verbal_fluency_animals',
      crfCode: 'N1.2.11',
      title: '词语流畅性（动物）',
      prompt: '请在 1 分钟内尽可能多地说出动物名称。',
      instruction: '记录用时和原始回答内容。',
      order: 12,
      groupCode: 'language',
      responseType: 'timed_task',
      scoreRange: { min: 0, max: 1, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['language'],
      evidenceTypes: ['duration', 'raw_text', 'operator_note'],
      requiresTimer: true,
      supportsPhotoUpload: false,
      supportsHandwriting: false,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'timed_manual',
        durationSeconds: 60,
        scoringSummary:
          '1 分钟内动物名称数量达到阈值给 1 分，并尽量详细记录回答内容。',
        recordCrfCode: 'N1.2.11.1',
        scoreCrfCode: 'N1.2.11.2',
      },
      qualityControlRule: {
        requireTimer: true,
        preserveRawText: true,
      },
      reportingRule: {
        showInReport: true,
        groupLabel: '语言',
      },
      researchExportField: 'moca_language_verbal_fluency_animals_score',
    },
    {
      code: 'moca.abstraction.train_bicycle',
      crfCode: 'N1.2.12.1',
      title: '抽象：火车和自行车',
      prompt: '请说明火车和自行车有什么共同点。',
      instruction: '抽象概括正确得 1 分。',
      order: 13,
      groupCode: 'abstraction',
      responseType: 'text',
      scoreRange: { min: 0, max: 1, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['abstraction'],
      evidenceTypes: ['raw_text', 'operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: false,
      supportsHandwriting: false,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'manual_concept_review',
        scoringSummary: '抽象共同类别回答正确得 1 分。',
        sourceCorrection: 'PDF 误写为 N1.2.11.1，系统修正为 N1.2.12.1。',
      },
      qualityControlRule: {
        correction: 'PDF 误写为 N1.2.11.1，系统修正为 N1.2.12.1。',
      },
      reportingRule: {
        showInReport: true,
        groupLabel: '抽象',
        correctedCrfCode: 'N1.2.12.1',
      },
      researchExportField: 'moca_abstraction_train_bicycle_score',
    },
    {
      code: 'moca.abstraction.watch_scale',
      crfCode: 'N1.2.12.2',
      title: '抽象：手表和秤',
      prompt: '请说明手表和秤有什么共同点。',
      instruction: '抽象概括正确得 1 分。',
      order: 14,
      groupCode: 'abstraction',
      responseType: 'text',
      scoreRange: { min: 0, max: 1, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['abstraction'],
      evidenceTypes: ['raw_text', 'operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: false,
      supportsHandwriting: false,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'manual_concept_review',
        scoringSummary: '抽象共同类别回答正确得 1 分。',
        sourceCorrection: 'PDF 误写为 N1.2.11.2，系统修正为 N1.2.12.2。',
      },
      qualityControlRule: {
        correction: 'PDF 误写为 N1.2.11.2，系统修正为 N1.2.12.2。',
      },
      reportingRule: {
        showInReport: true,
        groupLabel: '抽象',
        correctedCrfCode: 'N1.2.12.2',
      },
      researchExportField: 'moca_abstraction_watch_scale_score',
    },
    {
      code: 'moca.memory.delayed_recall',
      crfCode: 'N1.2.13',
      title: '延迟回忆',
      prompt: '先记录五个词的自由回忆，再记录分类提示和多选提示后的表现。',
      instruction:
        '只记录第一遍自由回忆的得分；提示后表现不计入自由回忆得分但必须保留。',
      order: 15,
      groupCode: 'delayed_recall',
      responseType: 'multi_choice',
      scoreRange: { min: 0, max: 5, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['memory'],
      evidenceTypes: ['raw_text', 'operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: false,
      supportsHandwriting: false,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'delayed_recall_with_prompt_records',
        scoringSummary:
          '只记录第一遍自由回忆的得分；分类提示和多选提示不计入自由回忆得分但必须保留。',
        scoreSource: 'free_recall_only',
        promptRecords: [
          {
            code: 'moca.memory.delayed_recall.face',
            word: '面孔',
            freeRecallScoreField: 'freeRecall',
            categoryCueRecordField: 'categoryCue',
            multipleChoiceCueRecordField: 'multipleChoiceCue',
          },
          {
            code: 'moca.memory.delayed_recall.silk',
            word: '丝绸',
            freeRecallScoreField: 'freeRecall',
            categoryCueRecordField: 'categoryCue',
            multipleChoiceCueRecordField: 'multipleChoiceCue',
          },
          {
            code: 'moca.memory.delayed_recall.school',
            word: '学校',
            freeRecallScoreField: 'freeRecall',
            categoryCueRecordField: 'categoryCue',
            multipleChoiceCueRecordField: 'multipleChoiceCue',
          },
          {
            code: 'moca.memory.delayed_recall.chrysanthemum',
            word: '菊花',
            freeRecallScoreField: 'freeRecall',
            categoryCueRecordField: 'categoryCue',
            multipleChoiceCueRecordField: 'multipleChoiceCue',
          },
          {
            code: 'moca.memory.delayed_recall.red',
            word: '红色',
            freeRecallScoreField: 'freeRecall',
            categoryCueRecordField: 'categoryCue',
            multipleChoiceCueRecordField: 'multipleChoiceCue',
          },
        ],
      },
      qualityControlRule: {
        preservePromptResponses: true,
        preserveRawText: true,
      },
      reportingRule: {
        showInReport: true,
        showPromptResponses: true,
      },
      researchExportField: 'moca_memory_delayed_recall_score',
    },
    {
      code: 'moca.orientation',
      crfCode: 'N1.2.14',
      title: '定向',
      prompt: '询问年、月份、日期、星期、地点和城市。',
      instruction: '每个定向子项正确得 1 分。',
      order: 16,
      groupCode: 'orientation',
      responseType: 'multi_choice',
      scoreRange: { min: 0, max: 6, step: 1 },
      countsTowardTotal: true,
      cognitiveDomainCodes: ['orientation'],
      evidenceTypes: ['operator_note'],
      requiresTimer: false,
      supportsPhotoUpload: false,
      supportsHandwriting: false,
      requiresOperatorNote: true,
      scoringRule: {
        mode: 'structured_manual',
        subItems: [
          { code: 'moca.orientation.year', title: '年', maxScore: 1 },
          { code: 'moca.orientation.month', title: '月份', maxScore: 1 },
          { code: 'moca.orientation.date', title: '日期', maxScore: 1 },
          { code: 'moca.orientation.weekday', title: '星期', maxScore: 1 },
          { code: 'moca.orientation.place', title: '地点', maxScore: 1 },
          { code: 'moca.orientation.city', title: '城市', maxScore: 1 },
        ],
      },
      qualityControlRule: {
        requireStructuredSubItems: true,
      },
      reportingRule: {
        showInReport: true,
        groupLabel: '定向',
      },
      researchExportField: 'moca_orientation_score',
    },
  ],
  qualityControlRules: {
    sourceDocument: 'MMSE+MoCA.pdf',
    preserveNonScoredRecords: true,
    corrections: [
      'MoCA 抽象项火车和自行车在附件中误写为 N1.2.11.1，系统修正为 N1.2.12.1。',
      'MoCA 抽象项手表和秤在附件中误写为 N1.2.11.2，系统修正为 N1.2.12.2。',
    ],
    evidenceConsistencyChecks: [
      'requiresTimer=true 时 evidenceTypes 应包含 duration。',
      'supportsPhotoUpload=true 时 evidenceTypes 应包含 photo。',
      'supportsHandwriting=true 时 evidenceTypes 应包含 handwriting。',
    ],
  },
  reportingRules: {
    showTotalScore: true,
    totalScoreCrfCode: 'N1.2.15',
    totalScoreField: 'moca_total_score',
    totalScoreRange: { min: 0, max: 30 },
    totalScoreNote: 'N1.2.15 为汇总字段，不作为独立计分题参与总分累加。',
    showEvidenceForItems: [
      'moca.visuospatial.trail_making',
      'moca.visuospatial.cube',
      'moca.visuospatial.clock',
    ],
  },
  researchExportMappings: {
    sourceDocument: 'MMSE+MoCA.pdf',
    totalScoreCrfCode: 'N1.2.15',
    totalScoreField: 'moca_total_score',
    itemScoreFields: {
      'moca.visuospatial.trail_making': 'moca_visuospatial_trail_making_score',
      'moca.visuospatial.cube': 'moca_visuospatial_cube_score',
      'moca.visuospatial.clock': 'moca_visuospatial_clock_score',
      'moca.language.naming_animals': 'moca_language_naming_animals_score',
      'moca.memory.immediate.trial_1': 'moca_memory_immediate_trial_1_record',
      'moca.memory.immediate.trial_2': 'moca_memory_immediate_trial_2_record',
      'moca.attention.digit_span_forward':
        'moca_attention_digit_span_forward_score',
      'moca.attention.digit_span_backward':
        'moca_attention_digit_span_backward_score',
      'moca.attention.vigilance': 'moca_attention_vigilance_score',
      'moca.attention.serial_sevens': 'moca_attention_serial_sevens_score',
      'moca.language.sentence_repetition':
        'moca_language_sentence_repetition_score',
      'moca.language.verbal_fluency_animals':
        'moca_language_verbal_fluency_animals_score',
      'moca.abstraction.train_bicycle': 'moca_abstraction_train_bicycle_score',
      'moca.abstraction.watch_scale': 'moca_abstraction_watch_scale_score',
      'moca.memory.delayed_recall': 'moca_memory_delayed_recall_score',
      'moca.orientation': 'moca_orientation_score',
    },
    evidenceFields: {
      'moca.visuospatial.trail_making.duration': 'N1.2.1.1',
      'moca.visuospatial.trail_making.photo': 'N1.2.1.2',
      'moca.visuospatial.cube.photo': 'N1.2.2.1',
      'moca.visuospatial.clock.photo': 'N1.2.3.1',
    },
  },
};

export const MOCA_SCALE_SEED: ScaleSeedData = {
  definition: MOCA_SCALE_DEFINITION_SEED,
  version: MOCA_SCALE_VERSION_SEED,
};
